title: Italo Carnevale

logo: profile.jpg

description: IT Enterprise Architect / Advisor

show_downloads: true

theme: jekyll-theme-minimal 

plugins:
  - jekyll-seo-tag

email: italocarnevale@gmail.com # Allow visitors to contact you
